# Generated by Django 4.1.5 on 2023-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postst_title',
            new_name='post_title',
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
