# Generated by Django 4.1.5 on 2023-04-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_rename_postst_title_post_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(),
        ),
    ]
